export const NAV_TEXT = {
  dashboard: "Gösterge",
  assets: "Varlıklar",
  maintenance: "Bakım",
  services: "Servisler",
  documents: "Belgeler",
  timeline: "Zaman Akışı",
  expenses: "Giderler",
  notifications: "Bildirimler",
  billing: "Abonelikler",
  invoices: "Fatura Takip",
  costs: "Skor Analizi",
  reports: "Raporlar",
  settings: "Ayarlar",
  panel: "Panel",
  detail: "Detay",
} as const;

export const SIDEBAR_TEXT = {
  ariaLabel: "Ana menü",
  freePlanLabel: "Deneme Planı",
  usageAssets: "Varlıklar",
  usageDocuments: "Belgeler",
  usageSubscriptions: "Abonelikler",
  usageInvoiceUploads: "Fatura Yükleme",
  upgradeCta: "Premium'a Geç",
  premiumMemberBadge: "Premium Üye",
  unlimitedAssetsStatus: "Sınırsız varlık aktif",
  nextInvoicePrefix: "Sonraki fatura",
  infiniteLimit: "∞",
} as const;

export const PAYMENT_TEXT = {
  stripeCollectionNotice: "Ödemeler Planicas LLC adına Stripe üzerinden güvenle tahsil edilir.",
} as const;

export const EXPENSES_TEXT = {
  defaultTitle: "Gider",
  defaultCategory: "Diğer",
  pageBadge: "Gider Takibi",
  pageTitle: "Giderler",
  pageSubtitle: "Giderlerinizi kaydedin ve varlık bazlı takip edin.",
  pageHeaderSubtitle: "Gider girişleri, özet metrikler ve gider listesi.",
  summaryTotalRecords: "Toplam Kayıt",
  summaryLinkedAssets: "Varlık Bağlantılı",
  summaryCategory: "Kategori",
  validationRequiredFields: "Başlık, kategori ve tarih zorunludur.",
  validationInvalidAmount: "Tutar geçersiz.",
  missingTableOnWrite: "Gider tablosu bulunamadı. Kayıt eklenemedi.",
  createdSuccess: "Gider kaydı eklendi.",
  tableWarningPrefix: "Gider tablosu şu an erişilebilir değil. Boş liste gösteriliyor.",
  formTitle: "Yeni Gider",
  formAssetLabel: "Varlık (Opsiyonel)",
  formAssetContinueWithoutSelection: "Varlık seçmeden devam et",
  formTitleLabel: "Başlık",
  formTitlePlaceholder: "Örnek: Filtre alımı",
  formCategoryLabel: "Kategori",
  formCategoryPlaceholder: "Örnek: Yedek Parça",
  formAmountLabel: "Tutar",
  formCurrencyLabel: "Para Birimi",
  formDateLabel: "Gider Tarihi",
  formDatePlaceholder: "gg.aa.yyyy",
  formNoteLabel: "Not",
  formNotePlaceholder: "Opsiyonel not",
  formSubmitDefault: "Gider Ekle",
  formSubmitPending: "Kaydediliyor...",
  tableTitle: "Giderler",
  tableLoading: "Yükleniyor...",
  tableEmpty: "Henüz gider kaydı yok.",
  tableHeadDate: "Tarih",
  tableHeadTitle: "Başlık",
  tableHeadCategory: "Kategori",
  tableHeadAsset: "Varlık",
  tableHeadAmount: "Tutar",
  tableHeadNote: "Not",
} as const;
