import {
  Bell,
  Clock3,
  CreditCard,
  FileText,
  FolderOpen,
  HandCoins,
  LayoutDashboard,
  Package,
  Receipt,
  Settings,
  TrendingUp,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import { SIDEBAR_NAV_ITEMS, type SidebarNavIconKey } from "@/constants/sidebar-nav";
import type {
  PreviewListMenuKey,
  PreviewMenuItem,
  PreviewMenuKey,
  PreviewTheme,
  RowItem,
} from "@/modules/landing-v2/components/panel-preview/types";

const LANDING_PREVIEW_MENU_KEYS: PreviewMenuKey[] = [
  "dashboard",
  "assets",
  "maintenance",
  "services",
  "documents",
  "timeline",
  "expenses",
  "notifications",
  "billing",
  "invoices",
  "costs",
  "reports",
];

export const previewThemeVars: PreviewTheme = {
  ["--auth-bg" as string]: "#050a18",
  ["--auth-sidebar-bg" as string]: "#070e20",
  ["--auth-foreground" as string]: "#e8ecf4",
  ["--auth-muted" as string]: "#90a3d0",
  ["--auth-muted-soft" as string]: "rgb(144 163 208 / 72%)",
  ["--auth-surface" as string]: "rgb(10 17 40 / 68%)",
  ["--auth-surface-strong" as string]: "rgb(10 17 40 / 84%)",
  ["--auth-surface-soft" as string]: "rgb(17 29 58 / 72%)",
  ["--auth-border" as string]: "rgb(35 58 100 / 62%)",
  ["--auth-border-soft" as string]: "rgb(35 58 100 / 45%)",
  ["--auth-primary" as string]: "#10efb5",
  ["--auth-accent" as string]: "#2cf7ff",
  ["--auth-ring" as string]: "rgb(16 239 181 / 62%)",
  ["--auth-shadow" as string]: "0 16px 34px rgb(5 10 24 / 52%)",
  ["--auth-shadow-soft" as string]: "0 10px 22px rgb(5 10 24 / 42%)",
  ["--auth-shadow-glow" as string]: "0 0 34px rgb(16 239 181 / 12%)",
  ["--auth-sidebar-width" as string]: "16rem",
};

const iconBySidebarKey: Record<SidebarNavIconKey, LucideIcon> = {
  dashboard: LayoutDashboard,
  package: Package,
  wrench: Wrench,
  "folder-open": FolderOpen,
  clock: Clock3,
  "hand-coins": HandCoins,
  bell: Bell,
  "credit-card": CreditCard,
  receipt: Receipt,
  "trending-up": TrendingUp,
  "file-text": FileText,
  settings: Settings,
};

const previewContentByMenuKey: Record<PreviewMenuKey, Pick<PreviewMenuItem, "title" | "subtitle">> = {
  dashboard: {
    title: "Kontrol Merkezi",
    subtitle: "Özet metrikler, hızlı aksiyonlar ve risk paneli",
  },
  assets: {
    title: "Varlıklar",
    subtitle: "Varlık durumu, garanti ve son hareket görünümü",
  },
  maintenance: {
    title: "Bakım",
    subtitle: "Bakım kuralları, kritik tarihler ve sorumlu ekip",
  },
  services: {
    title: "Servis Kayıtları",
    subtitle: "Servis kayıtları, tedarikçi ve maliyet özeti",
  },
  documents: {
    title: "Belgeler",
    subtitle: "Belge durumu, eksikler ve doğrulama akışı",
  },
  timeline: {
    title: "Zaman Akışı",
    subtitle: "Son aktiviteler ve işlem günlüğü",
  },
  expenses: {
    title: "Giderler",
    subtitle: "Kategori bazlı gider ve tahmini maliyet",
  },
  notifications: {
    title: "Bildirimler",
    subtitle: "Risk, hatırlatma ve sistem sinyalleri",
  },
  billing: {
    title: "Abonelikler",
    subtitle: "Plan, ek paket ve yenileme görünümü",
  },
  invoices: {
    title: "Fatura Takip",
    subtitle: "Vade tarihi, fatura durumu ve tahsilat takibi",
  },
  costs: {
    title: "Skor Analizi",
    subtitle: "Kategori skorları ve etki düzeyi",
  },
  reports: {
    title: "Raporlar",
    subtitle: "Hazır raporlar ve son oluşturma geçmişi",
  },
  settings: {
    title: "Ayarlar",
    subtitle: "Profil, güvenlik ve plan tercihleri",
  },
};

export const previewMenuItems = SIDEBAR_NAV_ITEMS.filter((item) => LANDING_PREVIEW_MENU_KEYS.includes(item.key)).map(
  (item) => ({
    key: item.key,
    label: item.label,
    badge: item.shortCode,
    icon: iconBySidebarKey[item.iconKey],
    ...previewContentByMenuKey[item.key],
  }),
);

export const rowDataByMenu: Record<PreviewListMenuKey, RowItem[]> = {
  assets: [
    { title: "Klima B3", detail: "Merkez Ofis • HVAC", badge: "Aktif", date: "18 Mart 2026", amount: "48.000 TL" },
    {
      title: "Jeneratör A1",
      detail: "Depo Blok A • Enerji",
      badge: "Bakım Yaklaşıyor",
      date: "20 Mart 2026",
      amount: "128.500 TL",
    },
    {
      title: "Pompa C7",
      detail: "Üretim Hattı • Mekanik",
      badge: "Garanti Bitiyor",
      date: "24 Mart 2026",
      amount: "72.400 TL",
    },
    {
      title: "Laptop D12",
      detail: "Satın Alma • BT",
      badge: "Belge Eksik",
      date: "15 Mart 2026",
      amount: "36.900 TL",
    },
  ],
  maintenance: [
    {
      title: "Aylık filtre değişimi",
      detail: "Klima B3 • Sorumlu: Teknik Ekip",
      badge: "Kritik",
      date: "16 Mart 2026",
      amount: "1.850 TL",
    },
    {
      title: "500 saatlik bakım",
      detail: "Jeneratör A1 • Sorumlu: Servis Partneri",
      badge: "Yaklaşıyor",
      date: "21 Mart 2026",
      amount: "6.400 TL",
    },
    {
      title: "Titreşim kontrolü",
      detail: "Pompa C7 • Sorumlu: Mekanik Ekip",
      badge: "Planlandı",
      date: "22 Mart 2026",
      amount: "2.250 TL",
    },
    {
      title: "Batarya sağlık kontrolü",
      detail: "UPS Kabin 2 • Sorumlu: Elektrik Ekip",
      badge: "Aktif",
      date: "27 Mart 2026",
      amount: "1.120 TL",
    },
  ],
  services: [
    {
      title: "Yağ ve filtre değişimi",
      detail: "Jeneratör A1 • Atlas Teknik",
      badge: "Tamamlandı",
      date: "14 Mart 2026",
      amount: "4.780 TL",
    },
    {
      title: "Gaz basıncı kalibrasyonu",
      detail: "Klima B3 • Serin Mekanik",
      badge: "Onaylandı",
      date: "11 Mart 2026",
      amount: "2.340 TL",
    },
    {
      title: "Mil hizalama",
      detail: "Pompa C7 • Mekanik Destek",
      badge: "Bekliyor",
      date: "09 Mart 2026",
      amount: "3.150 TL",
    },
    {
      title: "SSD değişimi",
      detail: "Laptop D12 • Nova Bilişim",
      badge: "Planlandı",
      date: "08 Mart 2026",
      amount: "1.980 TL",
    },
  ],
  documents: [
    {
      title: "Jeneratör A1 Garanti Belgesi.pdf",
      detail: "Garanti • Son yükleyen: Osman Y.",
      badge: "Onaylandı",
      date: "12 Mart 2026",
      amount: "2,4 MB",
    },
    {
      title: "Klima B3 Servis Formu.pdf",
      detail: "Servis kaydı • İmza bekliyor",
      badge: "İnceleniyor",
      date: "10 Mart 2026",
      amount: "1,8 MB",
    },
    {
      title: "Pompa C7 CE Sertifikası.pdf",
      detail: "Uyumluluk • Süre bitimine 14 gün",
      badge: "Garanti Bitiyor",
      date: "06 Mart 2026",
      amount: "3,1 MB",
    },
    {
      title: "Laptop D12 Teslim Tutanağı.pdf",
      detail: "Evrak akışı • Yükleme eksik",
      badge: "Belge Eksik",
      date: "05 Mart 2026",
      amount: "0,9 MB",
    },
  ],
  timeline: [
    {
      title: "Servis kaydı kapatıldı",
      detail: "Jeneratör A1 periyodik servis maliyeti işlendi",
      badge: "Bugün 10:24",
      date: "18 Mart 2026",
      amount: "4.780 TL",
    },
    {
      title: "Belge kontrolü tamamlandı",
      detail: "Klima B3 servis formu incelemeye alındı",
      badge: "Bugün 08:40",
      date: "18 Mart 2026",
      amount: "Belge",
    },
    {
      title: "Bakım uyarısı üretildi",
      detail: "Pompa C7 için 3 gün içinde titreşim kontrolü var",
      badge: "Dün 17:15",
      date: "17 Mart 2026",
      amount: "Uyarı",
    },
    {
      title: "Yeni varlık eklendi",
      detail: "Laptop D12 satın alma kaydı oluşturuldu",
      badge: "Dün 11:05",
      date: "17 Mart 2026",
      amount: "Varlık",
    },
  ],
  expenses: [
    {
      title: "Jeneratör A1 periyodik servis",
      detail: "Bakım • Atlas Teknik",
      badge: "Servis",
      date: "14 Mart 2026",
      amount: "4.780 TL",
    },
    {
      title: "Klima B3 filtre seti",
      detail: "Yedek Parça • HVAC",
      badge: "Parça",
      date: "13 Mart 2026",
      amount: "1.260 TL",
    },
    {
      title: "Pompa C7 rulman değişimi",
      detail: "Acil Müdahale • Mekanik",
      badge: "Acil",
      date: "09 Mart 2026",
      amount: "7.940 TL",
    },
    {
      title: "Laptop D12 SSD yükseltmesi",
      detail: "BT Donanım • Nova Bilişim",
      badge: "Operasyon",
      date: "08 Mart 2026",
      amount: "1.980 TL",
    },
  ],
  notifications: [
    {
      title: "Bakım gecikmesi",
      detail: "Klima B3 filtre değişimi 2 gün gecikti",
      badge: "Kritik",
      date: "18 Mart 2026 • 10:12",
      amount: "Aksiyon al",
    },
    {
      title: "Garanti bitiyor",
      detail: "Jeneratör A1 garantisi için 4 gün kaldı",
      badge: "Uyarı",
      date: "18 Mart 2026 • 08:05",
      amount: "Detaya git",
    },
    {
      title: "Belge eksik",
      detail: "Laptop D12 teslim tutanağı henüz yüklenmedi",
      badge: "Bilgi",
      date: "17 Mart 2026 • 16:40",
      amount: "Belge yükle",
    },
    {
      title: "Skor artışı",
      detail: "Bu hafta genel sağlık skoru +4 puan yükseldi",
      badge: "Bilgi",
      date: "17 Mart 2026 • 09:18",
      amount: "+4",
    },
  ],
  billing: [
    {
      title: "Assetly Premium",
      detail: "25 kullanıcı • Premium plan",
      badge: "Aktif",
      date: "12 Nisan 2026",
      amount: "2.490 TL",
    },
    {
      title: "SMS Bildirim Paketi",
      detail: "2.000 SMS / ay",
      badge: "Yenileniyor",
      date: "01 Nisan 2026",
      amount: "690 TL",
    },
    {
      title: "Bulut Yedekleme",
      detail: "500 GB arşiv alanı",
      badge: "Aktif",
      date: "06 Nisan 2026",
      amount: "420 TL",
    },
    {
      title: "Saha Ekibi Modülü",
      detail: "Ek lisans • 6 kullanıcı",
      badge: "Planlandı",
      date: "25 Mart 2026",
      amount: "960 TL",
    },
  ],
  invoices: [
    {
      title: "Elektrik Aboneliği",
      detail: "Mart 2026 tüketim faturası",
      badge: "Yaklaşıyor",
      date: "22 Mart 2026",
      amount: "3.420 TL",
    },
    {
      title: "Assetly Premium",
      detail: "Nisan 2026 lisans yenilemesi",
      badge: "Planlandı",
      date: "01 Nisan 2026",
      amount: "2.490 TL",
    },
    {
      title: "Yedek Parça Tedariği",
      detail: "Pompa C7 rulman faturası",
      badge: "Gecikme",
      date: "12 Mart 2026",
      amount: "7.940 TL",
    },
    {
      title: "Bulut Yedekleme",
      detail: "Mart 2026 hizmet bedeli",
      badge: "Ödendi",
      date: "07 Mart 2026",
      amount: "420 TL",
    },
  ],
  costs: [
    { title: "Bakım Uyum Skoru", detail: "Son 30 gün", badge: "82", date: "18 Mart 2026", amount: "Orta Etki" },
    { title: "Belge Tamamlılık", detail: "Arşiv kapsama oranı", badge: "74", date: "17 Mart 2026", amount: "Yüksek Etki" },
    { title: "Ödeme Disiplini", detail: "Tahsilat ve vade uyumu", badge: "91", date: "18 Mart 2026", amount: "Düşük Etki" },
    { title: "Varlık Sağlığı", detail: "Risk ve servis dengesi", badge: "88", date: "18 Mart 2026", amount: "Pozitif Trend" },
  ],
  reports: [
    {
      title: "Aylık Operasyon Özeti.pdf",
      detail: "Mart 2026 • 14 varlık grubu",
      badge: "Hazır",
      date: "18 Mart 2026",
      amount: "PDF",
    },
    {
      title: "Bakım Uyum Raporu.pdf",
      detail: "Son 30 gün",
      badge: "Hazır",
      date: "17 Mart 2026",
      amount: "PDF",
    },
    {
      title: "Servis Maliyet Analizi.pdf",
      detail: "Q1 2026",
      badge: "Hazır",
      date: "16 Mart 2026",
      amount: "PDF",
    },
    {
      title: "Skor Trend Raporu.pdf",
      detail: "Haftalık özet",
      badge: "Hazır",
      date: "15 Mart 2026",
      amount: "PDF",
    },
  ],
  settings: [
    { title: "Profil Bilgileri", detail: "Osman Yılmaz", badge: "Güncel", date: "21 Şubat 2026", amount: "Profil" },
    { title: "Plan Yönetimi", detail: "Premium Aylık", badge: "Aktif", date: "18 Şubat 2026", amount: "Plan" },
    { title: "Güvenlik", detail: "2FA Aktif", badge: "Güvenli", date: "17 Şubat 2026", amount: "Ayar" },
  ],
};
