begin;

create table if not exists public.auth_fraud_events (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  event text not null,
  created_at timestamptz not null default now()
);

create index if not exists auth_fraud_events_ip_created_at_idx
  on public.auth_fraud_events (ip_hash, created_at desc);

create index if not exists auth_fraud_events_ip_event_created_at_idx
  on public.auth_fraud_events (ip_hash, event, created_at desc);

alter table public.auth_fraud_events enable row level security;

revoke all on table public.auth_fraud_events from anon, authenticated, public;
grant all on table public.auth_fraud_events to service_role;

commit;
